In [1]:
import pandas as pd
import numpy as np

In [2]:
#Set max row display to 1000
pd.set_option('display.max_row', 1000)

In [3]:
Jan2021data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2021-01-02/visualisations/listings.csv')
Dec2020data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2020-12-12/visualisations/listings.csv')
Nov2020data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2020-11-03/visualisations/listings.csv')
Oct2020data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2020-10-09/visualisations/listings.csv')
Sep2020data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2020-09-09/visualisations/listings.csv')
Aug2020data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2020-08-18/visualisations/listings.csv')
Jul2020data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2020-07-09/visualisations/listings.csv')
Jun2020data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2020-06-08/visualisations/listings.csv')
May2020data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2020-05-07/visualisations/listings.csv')
Apr2020data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2020-04-09/visualisations/listings.csv')
Mar2020data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2020-03-16/visualisations/listings.csv')
Feb2020data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2020-02-14/visualisations/listings.csv')
Jan2020data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2020-01-07/visualisations/listings.csv')
Dec2019data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2019-12-07/visualisations/listings.csv')
Nov2019data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2019-11-03/visualisations/listings.csv')
Oct2019data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2019-10-15/visualisations/listings.csv')
Sep2019data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2019-09-14/visualisations/listings.csv')
Aug2019data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2019-08-08/visualisations/listings.csv')
Jul2019data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2019-07-08/visualisations/listings.csv')
Jun2019data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2019-06-04/visualisations/listings.csv')
May2019data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2019-05-06/visualisations/listings.csv')
Apr2019data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2019-04-08/visualisations/listings.csv')
Mar2019data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2019-03-07/visualisations/listings.csv')
Feb2019data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2019-02-04/visualisations/listings.csv')
Jan2019data = pd.read_csv('http://data.insideairbnb.com/canada/on/toronto/2019-01-13/visualisations/listings.csv')

In [4]:
Jan2021data['date_compiled'] = pd.Timestamp('2021-01-02')
Jan2021data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
18260,47376260,"Private Ensuite room, Comfy Guest House, Toronto",138145,Comfy Guest House,NaN,Moss Park,43.66206,-79.36938,Private room,79,2,0,NaN,NaN,1,245,2021-01-02
18261,47376858,Modern Nice and Cozy 3Bedroom House in Scarbor...,61575224,Sean,NaN,Woburn,43.77640,-79.22799,Entire home/apt,222,1,0,NaN,NaN,4,364,2021-01-02
18262,47377779,Private Bedroom Downtown Toronto,317648405,Dan,NaN,Dovercourt-Wallace Emerson-Junction,43.67071,-79.42656,Private room,31,1,0,NaN,NaN,2,103,2021-01-02
18263,47389938,"2 Bedrooms, 1 Bathroom YONGE & SHEPPARD - YS25FL1",12742095,Emil & Sue,NaN,Willowdale East,43.76257,-79.41037,Entire home/apt,115,28,0,NaN,NaN,29,334,2021-01-02
18264,47390017,"Lakeview Condo, CN Tower, Free Parking, Mthly ...",91170750,Yawen,NaN,Waterfront Communities-The Island,43.63958,-79.39742,Entire home/apt,55,28,0,NaN,NaN,1,31,2021-01-02

In [5]:
Dec2020data['date_compiled'] = pd.Timestamp('2020-12-12')
Dec2020data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
18548,46970103,Elegant House near Yonge and Sheppard,19657311,Gloria Geum Lee,NaN,Lansing-Westgate,43.75710,-79.42384,Private room,40,28,0,NaN,NaN,3,365,2020-12-12
18549,46972809,Master Bedroom Queen St West Downtown Toronto,199185278,Jason,NaN,Trinity-Bellwoods,43.64682,-79.40736,Private room,44,2,0,NaN,NaN,3,90,2020-12-12
18550,46973070,Newly Renovated Private & Cozy 3rd Floor,379361883,Krystal,NaN,Forest Hill North,43.70957,-79.41880,Private room,40,30,0,NaN,NaN,3,344,2020-12-12
18551,46974551,Luxury Family Home in one of Toronto's Best Areas,140468739,Eugene,NaN,Mount Pleasant East,43.69941,-79.38191,Entire home/apt,230,30,0,NaN,NaN,1,301,2020-12-12
18552,46982295,生活套房公寓一卧公寓房,151117050,Adriana,NaN,Waterfront Communities-The Island,43.63948,-79.39624,Private room,39,1,0,NaN,NaN,1,0,2020-12-12

In [6]:
Nov2020data['date_compiled'] = pd.Timestamp('2020-11-03')
Nov2020data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
18801,46197136,SPECIAL RATE!-1 bed/1 bth-Furnished-300 Front,169697179,DelSuites,NaN,Waterfront Communities-The Island,43.644910,-79.389760,Entire home/apt,85,30,0,NaN,NaN,28,83,2020-11-03
18802,46198668,Private Apt 5-Star LocationDowntownToronto,311805447,Anthony,NaN,Kensington-Chinatown,43.653780,-79.402140,Entire home/apt,48,1,0,NaN,NaN,3,90,2020-11-03
18803,46200413,Super Cozy Private Apartment Downtown TO Smart TV,311805447,Anthony,NaN,Kensington-Chinatown,43.651786,-79.400727,Entire home/apt,51,1,0,NaN,NaN,3,62,2020-11-03
18804,46200770,"Cozy Bedroom, Downtown Toronto, Smart TV",372316210,Ben,NaN,Kensington-Chinatown,43.651786,-79.400727,Private room,36,1,0,NaN,NaN,5,90,2020-11-03
18805,46201677,"Cozy Private Bedroom, Smart TV 15min to Airport",341626040,Jean,NaN,Caledonia-Fairbank,43.692739,-79.453902,Private room,34,2,0,NaN,NaN,2,90,2020-11-03

In [7]:
Oct2020data['date_compiled'] = pd.Timestamp('2020-10-09')
Oct2020data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
18741,45785334,Bright & Luxurious 1 Bdr-Apt In Heart of Toronto,1023135,Sha,NaN,Yonge-Eglinton,43.70703,-79.40052,Entire home/apt,65,90,0,NaN,NaN,1,344,2020-10-09
18742,45786222,"3 Cozy Bedrooms, Detached home, 3 Free Parking",371188170,Grace,NaN,Newtonbrook East,43.79075,-79.39699,Entire home/apt,158,90,0,NaN,NaN,1,179,2020-10-09
18743,45786961,Stunning View Condo,371195218,Nikta,NaN,Bayview Village,43.76668,-79.37158,Entire home/apt,70,1,0,NaN,NaN,1,0,2020-10-09
18744,45789233,"30% OFF Private Bedroom, Queen Size Bed, Toronto",304805850,Daniel,NaN,Corso Italia-Davenport,43.67330,-79.44542,Private room,39,1,0,NaN,NaN,2,52,2020-10-09
18745,45789708,Private Apartment Amazing Downtown TO Location,344709977,James,NaN,Niagara,43.64481,-79.40677,Entire home/apt,52,1,0,NaN,NaN,1,33,2020-10-09

In [8]:
Sep2020data['date_compiled'] = pd.Timestamp('2020-09-09')
Sep2020data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
19338,45348297,Studio Condo in Downtown Toronto #5,342316738,Davar,NaN,Church-Yonge Corridor,43.649440,-79.376090,Private room,99,30,0,NaN,NaN,24,264,2020-09-09
19339,45351124,budget friendly nice place,342346982,Edip,NaN,Mount Pleasant West,43.699408,-79.390239,Shared room,37,1,0,NaN,NaN,7,365,2020-09-09
19340,45351175,"affordable, long term place :)",342346982,Edip,NaN,Yonge-St.Clair,43.693933,-79.397942,Shared room,29,1,0,NaN,NaN,7,364,2020-09-09
19341,45351235,Studio Unit with a nice view :),342346982,Edip,NaN,Yonge-Eglinton,43.706643,-79.401303,Entire home/apt,111,1,0,NaN,NaN,7,365,2020-09-09
19342,45351322,Luxury Studio Condo Amazing LakeView,38189462,Frankie,NaN,Waterfront Communities-The Island,43.642040,-79.383045,Entire home/apt,111,2,0,NaN,NaN,3,22,2020-09-09

In [9]:
Aug2020data['date_compiled'] = pd.Timestamp('2020-08-18')
Aug2020data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
19570,44952208,Amazing 2 Bedroom Suite in home - Private Entr...,362188889,Eric,NaN,Clanton Park,43.74964,-79.44289,Entire home/apt,126,1,0,NaN,NaN,2,35,2020-08-18
19571,44955917,FOODPV Rm2x/Toronto Downtown Private Bath/Entr...,291533774,Davy,NaN,Kensington-Chinatown,43.64937,-79.40407,Private room,65,1,0,NaN,NaN,5,3,2020-08-18
19572,44956441,"1 BR/1BA Condo with Balcony, High Floor near T...",263009685,Adrienne,NaN,Waterfront Communities-The Island,43.64246,-79.38159,Entire home/apt,96,1,0,NaN,NaN,9,97,2020-08-18
19573,44958080,Family style 1+Den condo for reasonable price,162975635,Manasa,NaN,Clanton Park,43.75376,-79.44362,Entire home/apt,65,60,0,NaN,NaN,1,91,2020-08-18
19574,44963429,Cosy apartment in Beaches/Leslieville (short t...,71296587,Christopher,NaN,Greenwood-Coxwell,43.66942,-79.31958,Entire home/apt,68,15,0,NaN,NaN,1,79,2020-08-18

In [10]:
Jul2020data['date_compiled'] = pd.Timestamp('2020-07-09')
Jul2020data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
20521,44138040,Jr One bedroom Fully Furnished Condo #7,342316738,Davar,NaN,Church-Yonge Corridor,43.64936,-79.37664,Entire home/apt,99,30,0,NaN,NaN,14,178,2020-07-09
20522,44138147,"Sunset soothes, mornings dictate",67926033,Margarita,NaN,Edenbridge-Humber Valley,43.65986,-79.51681,Entire home/apt,60,1,0,NaN,NaN,1,159,2020-07-09
20523,44138518,Small Semi-detached home,352603587,Jason,NaN,South Riverdale,43.66773,-79.32685,Entire home/apt,301,3,0,NaN,NaN,1,3,2020-07-09
20524,44138982,Deluxe11 - Platinum- 2 Bed 2 Bath Luxury Suite,334021955,Thampi,NaN,Niagara,43.64468,-79.40793,Entire home/apt,398,1,0,NaN,NaN,3,365,2020-07-09
20525,44139778,Downtown Annex rooftop retreat-Covid free clea...,7788565,Dino,NaN,Annex,43.66880,-79.41205,Entire home/apt,140,3,0,NaN,NaN,3,202,2020-07-09

In [11]:
Jun2020data['date_compiled'] = pd.Timestamp('2020-06-08')
Jun2020data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
21161,43708277,Lawrence Park Executive Home,63141512,Alison,NaN,Lawrence Park North,43.730395,-79.394289,Entire home/apt,401,7,0,NaN,NaN,1,80,2020-06-08
21162,43708692,Brand New Private Room Yonge & Wellesley,290388456,Wenying,NaN,Bay Street Corridor,43.665091,-79.384862,Private room,90,1,0,NaN,NaN,1,281,2020-06-08
21163,43709791,Beautiful luxurious house by lakeshore,30305712,Elina,NaN,Mimico (includes Humber Bay Shores),43.618319,-79.491775,Entire home/apt,450,2,0,NaN,NaN,2,83,2020-06-08
21164,43710831,"*NEW* Breathtaking, Large, Private, Corner Unit",30671009,Margarita,NaN,Waterfront Communities-The Island,43.645495,-79.393382,Entire home/apt,275,3,0,NaN,NaN,2,88,2020-06-08
21165,43712409,Fully Furnished Premium Condo Yonge & Sheppard...,110986914,Executive Furnished,NaN,Willowdale East,43.759639,-79.409337,Entire home/apt,200,3,0,NaN,NaN,30,90,2020-06-08

In [12]:
May2020data['date_compiled'] = pd.Timestamp('2020-05-07')
May2020data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
21766,43372389,"30% OFF Cozy Bedroom Easy Public Transit, Toronto",326152628,Hugo,NaN,Caledonia-Fairbank,43.686280,-79.459550,Private room,200,14,0,NaN,NaN,3,55,2020-05-07
21767,43374755,Exclusive luxury condo,154950119,Elina,NaN,North St.James Town,43.671680,-79.376490,Entire home/apt,190,30,0,NaN,NaN,1,358,2020-05-07
21768,43374824,"3 min Walk to subway, Plain but with all you n...",243664501,Mooim,NaN,Willowdale East,43.761332,-79.406131,Private room,37,10,0,NaN,NaN,9,24,2020-05-07
21769,43374905,Newly Renovated 2 Bedroom Luxury Condo WithPar...,180063042,Erdem,NaN,Henry Farm,43.773690,-79.330850,Entire home/apt,110,3,0,NaN,NaN,2,362,2020-05-07
21770,43375031,High Park 630 sqr ft. Basement w/separate entr...,292527083,Weiyun,NaN,High Park North,43.660090,-79.464130,Entire home/apt,200,2,0,NaN,NaN,4,0,2020-05-07

In [13]:
Apr2020data['date_compiled'] = pd.Timestamp('2020-04-09')
Apr2020data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
22420,43140581,Ent District 2BDR Style + Parking + Amenities,266939395,Curtis,NaN,Waterfront Communities-The Island,43.63773,-79.39842,Entire home/apt,84,1,0,NaN,NaN,3,0,2020-04-09
22421,43140887,01 room around York U Subway Masks are provided,43488381,Runying,NaN,York University Heights,43.76961,-79.49760,Private room,36,3,0,NaN,NaN,34,365,2020-04-09
22422,43142361,"New listing! Bright, Spacious High Park Apartment",4260847,David,NaN,High Park North,43.65745,-79.46697,Entire home/apt,101,4,0,NaN,NaN,1,53,2020-04-09
22423,43143239,14 York Street Condo,259270206,Jasmine,NaN,Waterfront Communities-The Island,43.64266,-79.38174,Entire home/apt,420,1,0,NaN,NaN,1,179,2020-04-09
22424,43144017,Trendy stylish loft on king W close to hospitals,16093144,Walid,NaN,Niagara,43.64115,-79.41322,Entire home/apt,149,30,0,NaN,NaN,1,81,2020-04-09

In [14]:
Mar2020data['date_compiled'] = pd.Timestamp('2020-03-16')
Mar2020data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
22999,42914765,Diamond suite-- No cleaning fee + free breakfast,167034435,Kevin,NaN,Moss Park,43.659400,-79.373280,Private room,199,1,0,NaN,NaN,21,364,2020-03-16
23000,42915363,STERILIZED CLEAN - Fashion District Luxury Condo,341738429,Daniel,NaN,Waterfront Communities-The Island,43.645490,-79.402840,Entire home/apt,109,1,0,NaN,NaN,1,107,2020-03-16
23001,42915787,Lovely Cosy and private space to feel like home,321259702,Alejandra,NaN,New Toronto,43.603536,-79.504276,Entire home/apt,40,1,0,NaN,NaN,1,140,2020-03-16
23002,42916243,Comfy bunkbed in a shared room in Scarborough TTC,327456656,Gevorg,NaN,Malvern,43.805905,-79.229054,Shared room,17,1,0,NaN,NaN,33,365,2020-03-16
23003,42917781,House in downtown Toronto,316319923,Peter,NaN,Moss Park,43.662442,-79.376491,Entire home/apt,498,6,0,NaN,NaN,2,349,2020-03-16

In [15]:
Feb2020data['date_compiled'] = pd.Timestamp('2020-02-14')
Feb2020data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
23393,42279466,Luxurious modern condo room,335942960,Atakan,NaN,Newtonbrook East,43.787228,-79.393602,Private room,36,1,0,NaN,NaN,1,45,2020-02-14
23394,42280836,Cozy House in North York,294307289,Walid,NaN,Willowdale West,43.772508,-79.427272,Entire home/apt,89,4,0,NaN,NaN,1,352,2020-02-14
23395,42281530,Your one stopover to a chilled apartment.,33106212,Dovid,NaN,Newtonbrook West,43.788057,-79.446452,Private room,34,1,0,NaN,NaN,1,48,2020-02-14
23396,42282147,Traveller’s spot,122215671,Julio Cesar,NaN,Taylor-Massey,43.694363,-79.291132,Shared room,30,1,0,NaN,NaN,1,82,2020-02-14
23397,42289607,Brand new modern studio,20356432,Tasawar,NaN,Church-Yonge Corridor,43.656841,-79.374769,Entire home/apt,150,7,0,NaN,NaN,1,172,2020-02-14

In [16]:
Jan2020data['date_compiled'] = pd.Timestamp('2020-01-07')
Jan2020data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
23519,41346460,"Bright, Renovated Etobicoke Home: 15m to Downtown",252562067,Angel Host,NaN,Islington-City Centre West,43.639810,-79.538360,Entire home/apt,110,1,0,NaN,NaN,2,178,2020-01-07
23520,41347750,★☼Budget Private Room Shared Kitchen & Living RM,23472830,Benjamin,NaN,East End-Danforth,43.690020,-79.295280,Private room,39,28,0,NaN,NaN,11,268,2020-01-07
23521,41348291,Quite space to relax,270056921,Shaydon,NaN,Regent Park,43.656230,-79.363250,Private room,104,1,0,NaN,NaN,2,365,2020-01-07
23522,41348626,Loft Style King Street 2 Bedroom - Free Parking,224508343,Brian,NaN,Waterfront Communities-The Island,43.645000,-79.396300,Entire home/apt,140,2,0,NaN,NaN,2,88,2020-01-07
23523,41351232,Comfort room on the Danforth,98407572,Michael,NaN,Danforth,43.683209,-79.324937,Private room,40,1,0,NaN,NaN,8,280,2020-01-07

In [17]:
Dec2019data['date_compiled'] = pd.Timestamp('2019-12-07')
Dec2019data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
23392,40647107,Anna小屋,212513433,Anna,NaN,Islington-City Centre West,43.632224,-79.518382,Shared room,60,3,0,NaN,NaN,1,32,2019-12-07
23393,40647659,Artsy Bed & Private Bathroom in Downtown,16057524,Jenn,NaN,Moss Park,43.657150,-79.354760,Private room,69,1,0,NaN,NaN,1,6,2019-12-07
23394,40650244,4 LOFTS- 6000 SQ FT-2-15 Bedrooms + Party Room,9443058,Kristle &Faisal,NaN,Kensington-Chinatown,43.653544,-79.395458,Entire home/apt,2000,1,0,NaN,NaN,22,98,2019-12-07
23395,40650884,4 Bed/8 ppl Lux Suite⭐CN Tower View⭐FREE Parking,310253541,Sam,NaN,Waterfront Communities-The Island,43.641790,-79.399519,Entire home/apt,186,1,0,NaN,NaN,1,52,2019-12-07
23396,40651493,Spacious Room 3-Min Walk to Subway (Female Only),145242773,Mel,NaN,York University Heights,43.765430,-79.495770,Private room,30,15,0,NaN,NaN,4,0,2019-12-07

In [18]:
Nov2019data['date_compiled'] = pd.Timestamp('2019-11-03')
Nov2019data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
22723,39820000,New home near Subway station,306348423,Ava,NaN,Henry Farm,43.77256,-79.33945,Private room,50,1,0,NaN,NaN,1,12,2019-11-03
22724,39820494,Minimalist cozy place - Near to public transport,110925975,Gabriela,NaN,Woodbine-Lumsden,43.68938,-79.31389,Shared room,50,1,0,NaN,NaN,1,63,2019-11-03
22725,39820779,Scarborough cozy basement with separate entrance,252654875,Tsering,NaN,Bendale,43.74712,-79.25812,Entire home/apt,78,1,0,NaN,NaN,1,365,2019-11-03
22726,39822833,clean spacious 2 bd unit with lake/cn tower vi...,80537662,Casper,NaN,Waterfront Communities-The Island,43.63949,-79.38047,Entire home/apt,601,3,0,NaN,NaN,1,82,2019-11-03
22727,39823462,5 Bedrooms + Large Detached Home - WIFI/Laundry,154959193,Vasim,NaN,Milliken,43.82960,-79.28035,Entire home/apt,150,1,0,NaN,NaN,1,226,2019-11-03

In [19]:
Oct2019data['date_compiled'] = pd.Timestamp('2019-10-15')
Oct2019data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
22211,39361273,Spectacular 2BR Executive Suite Financial Dist...,302339554,Andy,NaN,Bay Street Corridor,43.64947,-79.38267,Entire home/apt,130,3,0,NaN,NaN,1,199,2019-10-15
22212,39361355,Great full apartment in downtown,302338940,Michael,NaN,Church-Yonge Corridor,43.66043,-79.37972,Entire home/apt,149,2,0,NaN,NaN,1,87,2019-10-15
22213,39363059,Modern 2 BDR Condo - in the heart of DT Toronto,211673110,Guobin,NaN,Waterfront Communities-The Island,43.63768,-79.39907,Entire home/apt,149,1,0,NaN,NaN,1,256,2019-10-15
22214,39363272,Bright and beautiful one bed condo - waterfront,302346483,Charline,NaN,Waterfront Communities-The Island,43.64498,-79.36448,Entire home/apt,120,1,0,NaN,NaN,1,13,2019-10-15
22215,39367185,Beautiful Stay in North York Toronto,302387592,Johnny,NaN,Downsview-Roding-CFB,43.72995,-79.46457,Entire home/apt,130,1,0,NaN,NaN,1,73,2019-10-15

In [20]:
Sep2019data['date_compiled'] = pd.Timestamp('2019-09-14')
Sep2019data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
21895,38607091,One bedroom Private Quiet Comfy Midtown Apt.,290496503,Emre,NaN,Mount Pleasant East,43.70994,-79.38506,Entire home/apt,106,1,0,NaN,NaN,1,176,2019-09-14
21896,38607568,NEWLY RENOVATED ANNEX 3 BEDROOM BEAUTY,20379553,Joy,NaN,Annex,43.67308,-79.40744,Entire home/apt,83,3,0,NaN,NaN,1,258,2019-09-14
21897,38608462,2 bedroom basement Near Airport & Humber College,162875913,Rupinder,NaN,Mount Olive-Silverstone-Jamestown,43.73630,-79.58601,Entire home/apt,121,1,0,NaN,NaN,4,32,2019-09-14
21898,38609448,Bedroom near Airport & Humber College,162875913,Rupinder,NaN,Mount Olive-Silverstone-Jamestown,43.73630,-79.58601,Private room,70,1,0,NaN,NaN,4,78,2019-09-14
21899,38610028,Clean spacious bedrooms w lots of natural light,56766378,Sahar,NaN,Mount Pleasant West,43.71024,-79.39173,Private room,56,1,0,NaN,NaN,1,175,2019-09-14

In [21]:
Aug2019data['date_compiled'] = pd.Timestamp('2019-08-08')
Aug2019data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
21612,37571177,Friendly bachelor,273279554,Mitra,NaN,Newtonbrook East,43.79736,-79.41849,Entire home/apt,56,1,0,NaN,NaN,1,0,2019-08-08
21613,37571468,Queen Bed in Stockyards,283849803,James,NaN,Junction Area,43.67350,-79.47322,Private room,60,1,0,NaN,NaN,1,1,2019-08-08
21614,37578291,❤️HighRise Classy Condo in Biz District by Hi...,275038623,Robert,NaN,Bay Street Corridor,43.65101,-79.38285,Entire home/apt,200,1,0,NaN,NaN,18,362,2019-08-08
21615,37579902,❤️Penthouse Amazing View in Core Biz District TO,275038623,Robert,NaN,Bay Street Corridor,43.65101,-79.38285,Entire home/apt,200,1,0,NaN,NaN,18,365,2019-08-08
21616,37591207,Modern private room in Downtown Toronto!,39720022,Azita,NaN,Dovercourt-Wallace Emerson-Junction,43.66785,-79.42313,Private room,226,2,0,NaN,NaN,4,351,2019-08-08

In [22]:
Jul2019data['date_compiled'] = pd.Timestamp('2019-07-08')
Jul2019data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
21307,36505368,"Modern, elegant condo with panoramic views",274460050,Leon,NaN,Bay Street Corridor,43.66136,-79.38623,Entire home/apt,324,2,0,NaN,NaN,1,83,2019-07-08
21308,36505571,DOWNTOWN TORONTO CITY VIEW LUXURY SUITE.,274460567,Christian,NaN,Waterfront Communities-The Island,43.64602,-79.37467,Entire home/apt,500,3,0,NaN,NaN,1,89,2019-07-08
21309,36506892,A place by the Ravine,240720596,Hidulfa,NaN,Clairlea-Birchmount,43.71263,-79.27433,Private room,75,2,0,NaN,NaN,1,359,2019-07-08
21310,36511507,Prime Trinity Bellwoods Park location near Que...,14383797,Andrea,NaN,Trinity-Bellwoods,43.64823,-79.41169,Entire home/apt,250,30,0,NaN,NaN,1,311,2019-07-08
21311,36514152,Bright Beautiful Brilliant 2 Bedroom nearby su...,273422669,Gary,NaN,Henry Farm,43.77274,-79.34504,Entire home/apt,150,2,0,NaN,NaN,1,155,2019-07-08

In [23]:
Jun2019data['date_compiled'] = pd.Timestamp('2019-06-04')
Jun2019data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
20764,35373390,Kensington Market Cozy Private Unit,224566888,Ann,NaN,Kensington-Chinatown,43.65400,-79.40038,Entire home/apt,89,1,0,NaN,NaN,3,87,2019-06-04
20765,35376137,newly renovated single room in heart of dt Tor...,227634512,Nicole,NaN,Kensington-Chinatown,43.65215,-79.39659,Private room,85,2,0,NaN,NaN,9,6,2019-06-04
20766,35376802,newly renovated single room heart of dt Toronto,227634512,Nicole,NaN,Kensington-Chinatown,43.65163,-79.39617,Private room,85,2,0,NaN,NaN,9,21,2019-06-04
20767,35378234,"1 BR Modern Condo - Ent. District, MTCC, Jays",257889901,Lily,NaN,Waterfront Communities-The Island,43.64693,-79.39305,Entire home/apt,999,2,0,NaN,NaN,5,355,2019-06-04
20768,35383772,"New Loft Style - Private Terrace, Easy Parking",192794985,Adrian,NaN,Dovercourt-Wallace Emerson-Junction,43.66667,-79.41979,Entire home/apt,97,1,0,NaN,NaN,1,233,2019-06-04

In [24]:
May2019data['date_compiled'] = pd.Timestamp('2019-05-06')
May2019data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
20298,34449599,Convenience Hub,121442022,Birkan,NaN,Mount Pleasant West,43.71277,-79.39591,Private room,81,2,0,NaN,NaN,1,365,2019-05-06
20299,34449766,Cozy condo with amazing view of CN Tower <3,260067997,Sherry,NaN,Niagara,43.63760,-79.40648,Entire home/apt,119,2,0,NaN,NaN,2,17,2019-05-06
20300,34450478,"R2: Queen Size Bed Upstairs, Scarborough",109012911,Iouri,NaN,Tam O'Shanter-Sullivan,43.77689,-79.29251,Private room,34,1,0,NaN,NaN,1,176,2019-05-06
20301,34450621,Modern condo in heart of Toronto downtown!,260067997,Sherry,NaN,Bay Street Corridor,43.66689,-79.38622,Entire home/apt,99,2,0,NaN,NaN,2,14,2019-05-06
20302,34450758,Fully Furnished 4 Bedroom Upstairs of Bungalow,6110142,Yusuf,NaN,Newtonbrook West,43.78661,-79.42913,Entire home/apt,119,1,0,NaN,NaN,2,165,2019-05-06

In [25]:
Apr2019data['date_compiled'] = pd.Timestamp('2019-04-08')
Apr2019data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
20138,33684559,Beautiful 1 bedroom home in Toronto (queen bed),89113555,Nelly,NaN,Forest Hill North,43.70087,-79.43903,Entire home/apt,115,3,0,NaN,NaN,2,9,2019-04-08
20139,33685612,DOWNTOWN LUXURY 2BDRM 2BTH + PARKING,170567513,Golsana,NaN,Waterfront Communities-The Island,43.63859,-79.38437,Entire home/apt,150,2,0,NaN,NaN,5,200,2019-04-08
20140,33685686,"Master Room ""Ocean"" @ GTA transit hub Yonge Finch",100833811,Rachel,NaN,Newtonbrook East,43.78268,-79.41569,Private room,80,1,0,NaN,NaN,3,104,2019-04-08
20141,33688362,Make yourself at home!,176719438,Vijay,NaN,Henry Farm,43.77363,-79.34318,Private room,46,14,0,NaN,NaN,1,31,2019-04-08
20142,33690890,Enjoy Yorkville Skyline (2 bed + 2 bath + Park...,12478688,Ray,NaN,Annex,43.67114,-79.38717,Entire home/apt,298,3,0,NaN,NaN,9,347,2019-04-08

In [26]:
Mar2019data['date_compiled'] = pd.Timestamp('2019-03-07')
Mar2019data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
20031,32869854,"Downtown Convenience, Downtown Comfort",98737081,Cassie,NaN,Waterfront Communities-The Island,43.63972,-79.39470,Entire home/apt,145,2,0,NaN,NaN,1,4,2019-03-07
20032,32870150,The (Hidden by Airbnb) ad,4834923,Geoffrey,NaN,Yonge-St.Clair,43.69599,-79.39863,Entire home/apt,165,3,0,NaN,NaN,1,217,2019-03-07
20033,32870359,Cozy downtown studio,99988800,Sok,NaN,Niagara,43.64054,-79.41179,Entire home/apt,121,2,0,NaN,NaN,1,154,2019-03-07
20034,32871281,D&M apartment,10583403,Danijela,NaN,Yonge-St.Clair,43.69354,-79.39578,Entire home/apt,100,1,0,NaN,NaN,1,82,2019-03-07
20035,32872018,Davisville Weekend Airbnb,78297659,Kurt,NaN,Mount Pleasant West,43.69816,-79.39425,Shared room,40,1,0,NaN,NaN,1,83,2019-03-07

In [27]:
Feb2019data['date_compiled'] = pd.Timestamp('2019-02-04')
Feb2019data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
19880,32109624,"Unique, artistic 1 BDR plus Studio on Bloor line!",1408959,Jena,NaN,Dovercourt-Wallace Emerson-Junction,43.661760,-79.430452,Entire home/apt,100,1,0,NaN,NaN,2,365,2019-02-04
19881,32112571,CHIC TORONTO LOFT - ST.CLAIR AVE. W,37939368,L,NaN,Corso Italia-Davenport,43.676060,-79.447196,Entire home/apt,325,1,0,NaN,NaN,2,260,2019-02-04
19882,32113035,Amazing 42nd floor city view downtown Toronto,40861890,Christelle,NaN,Waterfront Communities-The Island,43.640727,-79.398062,Entire home/apt,135,1,0,NaN,NaN,1,89,2019-02-04
19883,32114055,Hullmark luxury fully furnished apartment,240924961,Howard,NaN,Willowdale East,43.762309,-79.410587,Entire home/apt,100,3,0,NaN,NaN,2,173,2019-02-04
19884,32114298,30 Roehampton luxury fully furnished apartment,240924961,Howard,NaN,Mount Pleasant West,43.707951,-79.397785,Entire home/apt,100,3,0,NaN,NaN,2,161,2019-02-04

In [28]:
Jan2019data['date_compiled'] = pd.Timestamp('2019-01-13')
Jan2019data.tail(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,date_compiled
19648,31517024,Best Value/$ for family accommodation in Toronto,147933259,Ayman,NaN,Clairlea-Birchmount,43.701751,-79.287846,Entire home/apt,61,3,0,NaN,NaN,6,263,2019-01-13
19649,31517341,Cozy room subway on side next to yonge street,157793742,Amirhossein,NaN,Willowdale West,43.777792,-79.416747,Private room,50,1,0,NaN,NaN,2,346,2019-01-13
19650,31517380,"The studio, with a private washroom",233703816,Pierce,NaN,Woodbine Corridor,43.677890,-79.313121,Private room,150,1,0,NaN,NaN,3,83,2019-01-13
19651,31518185,Trendy split level Apt. w exposed brick &freepark,18413679,Nicole,NaN,North Riverdale,43.669072,-79.342509,Entire home/apt,115,5,0,NaN,NaN,2,8,2019-01-13
19652,31518232,Modern One Bedroom Downtown Toronto,99635980,Gilda Suites,NaN,Niagara,43.638046,-79.403348,Entire home/apt,96,1,0,NaN,NaN,1,352,2019-01-13

In [29]:
#Concat all dfs into one

df = pd.concat([Jan2021data, Dec2020data, Nov2020data, Oct2020data, Sep2020data, Aug2020data, Jul2020data, Jun2020data, May2020data, Apr2020data, Mar2020data, Feb2020data, Jan2020data, Dec2019data, Nov2019data, Oct2019data, Sep2019data, Aug2019data, Jul2019data, Jun2019data, May2019data, Apr2019data, Mar2019data, Feb2019data, Jan2019data], ignore_index=True)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 523061 entries, 0 to 523060
Data columns (total 16 columns):
id                                523061 non-null int64
name                              523034 non-null object
host_id                           523061 non-null int64
host_name                         522547 non-null object
neighbourhood                     523061 non-null object
latitude                          523061 non-null float64
longitude                         523061 non-null float64
room_type                         523061 non-null object
price                             523061 non-null int64
minimum_nights                    523061 non-null int64
number_of_reviews                 523061 non-null int64
last_review                       421792 non-null object
reviews_per_month                 421792 non-null float64
calculated_host_listings_count    523061 non-null int64
availability_365                  523061 non-null int64
date_compiled                     523061 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(7), object(5)
memory usage: 63.9+ MB

In [34]:
#Can delete neighbourhood group, as there are zero measurements in this columns

del df['neighbourhood_group']

In [36]:
df.to_csv(r'C:\Users\jaypa\Documents\Data Projects\AirBNB\AirBNBdata.csv', index = False)